# Generated by Django 3.0 on 2019-12-16 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20191216_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proportion',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percent', to=settings.AUTH_USER_MODEL, verbose_name='付款人'),
        ),
    ]
