# Generated by Django 3.0.1 on 2019-12-21 00:50

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20191216_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='consume_at',
            field=models.DateField(default=datetime.date.today, verbose_name='消費日'),
        ),
        migrations.AddField(
            model_name='consume',
            name='description',
            field=models.TextField(blank=True, verbose_name='詳細資訊'),
        ),
        migrations.AddField(
            model_name='proportion',
            name='is_repaid',
            field=models.BooleanField(default=False, verbose_name='已還款'),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='description',
            field=models.TextField(blank=True, verbose_name='詳細資訊'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='未分類', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='proportion',
            unique_together={('username', 'consume')},
        ),
    ]
