# Generated by Django 3.0 on 2019-12-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191216_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='note',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='proportion',
            name='check_payment',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='accountbook',
            name='description',
            field=models.TextField(blank=True, verbose_name='詳細資訊'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
