# Generated by Django 3.0.1 on 2019-12-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191221_0244'),
        ('accounts', '0004_auto_20191221_0850'),
    ]

    operations = [
    ]
