# Generated by Django 3.0.1 on 2019-12-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191221_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='proportion',
            name='payment',
            field=models.PositiveIntegerField(default=0, verbose_name='還款'),
        ),
    ]
