# Generated by Django 3.0.1 on 2019-12-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_proportion_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proportion',
            name='check_payment',
        ),
    ]
