# Generated by Django 3.0.1 on 2019-12-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_proportion_check_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proportion',
            name='is_repaid',
        ),
    ]
